name: Verify

on: push

jobs:
  verify:
    name: Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: shellcheck
        run: docker run -v "$PWD":/mnt -w /mnt koalaman/shellcheck -- *.sh

  self_check:
    name: Run this Action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: ./
        with:
          command: greet
          who: world

      - uses: ./
        with:
          command: error
